# The URL the site will be built for
base_url = "https://davidolsen.dk/"

# The site title and description; used in feeds by default.
title = "David Søbæk Olsen"
description = "Hey, I'm David Søbæk Olsen from Denmark. I love programming, running, taking photos and learning new things!"

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The default author for pages
author = "David Søbæk Olsen"

# The taxonomies to be rendered for the site and their configuration of the default languages
taxonomies = [
  {name = "tags", feed = true, paginate_by = 10},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "charcoal"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = true

[extra]
long_title = "David Søbæk Olsen"
favicon = "/assets/images/profile.jpg"

[extra.footer]
source_code = "https://github.com/Nelsoon-ds/dvo-website"

[[extra.footer.socials]]
name = "mail"
label = "Email"
value = "david.s.olsen@hotmail.com"
link = "mailto:david.s.olsen@hotmail.com"
[[extra.footer.socials]]
name = "discord"
label = "Discord"
value = "Nelson"
link = "https://discord.com/users/200336783341256704"
[[extra.footer.socials]]
name = "LinkedIn"
label = "LinkedIn"
value = "davidolsen108"
link = "https://www.linkedin.com/in/davidolsen108/"

[[extra.links]]
name = "Home"
path = "/"
[[extra.links]]
name = "CV"
path = "/cv/"
